description = "Generate and maintain API documentation using OpenAPI specification. This command handles API documentation operations following the project's documentation standards."

prompt = """

Generate and maintain API documentation using OpenAPI specification.

This command handles API documentation operations following the project's documentation standards.

Given the documentation request provided as an argument, do this:

1. Run `scripts/api-documentation.sh --json "{{args}}"` from repo root and parse JSON for DOC_TYPE, ENDPOINT_PATH, SCHEMA_NAME, and OUTPUT_FORMAT. All file paths must be absolute.

2. Based on the documentation type, execute the appropriate documentation operation:
   - **generate-spec**: Generate OpenAPI specification from code
   - **update-endpoint**: Update specific endpoint documentation
   - **create-schema**: Create new schema definition
   - **validate-spec**: Validate OpenAPI specification
   - **serve-docs**: Serve interactive documentation
   - **export-postman**: Export Postman collection
   - **generate-client**: Generate client SDKs

3. For each operation, follow the API documentation protocol:
   - **Code Analysis**: Scan codebase for API endpoints and schemas
   - **Specification Generation**: Create or update OpenAPI specification
   - **Validation**: Verify specification compliance and completeness
   - **Documentation Generation**: Generate interactive documentation
   - **Client Generation**: Create client SDKs if requested

4. Enforce documentation standards:
   - Follow OpenAPI 3.0.3 specification
   - Include comprehensive examples
   - Validate schema definitions
   - Ensure endpoint completeness
   - Maintain version consistency

5. Generate documentation artifacts:
   - OpenAPI specification file
   - Interactive Swagger UI
   - Postman collection
   - Client SDKs (TypeScript, Python, etc.)
   - API reference documentation

6. Report completion with documentation type, generated files, and validation status.

Use absolute paths with the repository root for all file operations to avoid path issues.
"""
