description = "Execute code quality analysis and improvement operations. This command handles code quality operations following the project's quality guidelines and best practices."

prompt = """

Execute code quality analysis and improvement operations.

This command handles code quality operations following the project's quality guidelines and best practices.

Given the code quality request provided as an argument, do this:

1. Run `scripts/code-quality.sh --json "{{args}}"` from repo root and parse JSON for QUALITY_TYPE, ANALYSIS_SCOPE, METRICS_THRESHOLD, and IMPROVEMENT_LEVEL. All file paths must be absolute.

2. Based on the quality type, execute the appropriate code quality operation:
   - **analyze-quality**: Analyze code quality metrics
   - **run-linting**: Execute code linting and formatting
   - **check-complexity**: Analyze code complexity
   - **measure-coverage**: Measure test coverage
   - **detect-duplicates**: Find code duplication
   - **improve-readability**: Improve code readability
   - **optimize-performance**: Optimize code performance

3. For each quality operation, follow the code quality protocol:
   - **Code Analysis**: Analyze code for quality issues
   - **Metrics Collection**: Collect quality metrics and statistics
   - **Issue Identification**: Identify quality problems and improvements
   - **Improvement Implementation**: Implement quality improvements
   - **Validation**: Verify quality improvements
   - **Documentation**: Document quality findings and improvements

4. Enforce code quality best practices:
   - Follow coding standards
   - Maintain low complexity
   - Ensure good test coverage
   - Avoid code duplication
   - Write readable code
   - Optimize performance

5. Generate quality report:
   - Document quality metrics
   - List identified issues
   - Report improvement implementations
   - Provide quality recommendations
   - Include trend analysis

6. Report completion with quality type, analysis results, and improvement status.

Use absolute paths with the repository root for all file operations to avoid path issues.
"""
