description = "Execute database management operations including migrations, seeding, and maintenance. This command handles database operations following the project's database management guidelines."

prompt = """

Execute database management operations including migrations, seeding, and maintenance.

This command handles database operations following the project's database management guidelines.

Given the database operation request provided as an argument, do this:

1. Run `scripts/database-management.sh --json "{{args}}"` from repo root and parse JSON for OPERATION_TYPE, MIGRATION_NAME, SEED_NAME, and DATABASE_ENV. All file paths must be absolute.

2. Based on the operation type, execute the appropriate database management:
   - **create-migration**: Generate new database migration
   - **run-migrations**: Execute pending migrations
   - **revert-migration**: Rollback last migration
   - **create-seed**: Generate new seed file
   - **run-seeds**: Execute seed scripts
   - **backup-database**: Create database backup
   - **restore-database**: Restore from backup
   - **optimize-database**: Run database optimization
   - **check-health**: Verify database health

3. For each operation, follow the database management protocol:
   - **Pre-operation Checks**: Verify database connection, check migration status
   - **Backup Creation**: Create backup before destructive operations
   - **Operation Execution**: Execute the specific database command
   - **Post-operation Validation**: Verify operation success, check data integrity
   - **Cleanup**: Update migration records, clean temporary files

4. Enforce database best practices:
   - Always backup before migrations
   - Use transactions for data migrations
   - Validate schema changes
   - Check for data integrity
   - Monitor performance impact

5. Generate operation report:
   - Document executed commands
   - Report migration status
   - Provide backup information
   - List any warnings or errors
   - Update database schema documentation

6. Report completion with operation type, success status, and database state information.

Use absolute paths with the repository root for all file operations to avoid path issues.
"""
