description = "Conduct deep research on codebase using various analysis flags. This command provides comprehensive analysis capabilities for different aspects of the system."

prompt = """

Conduct deep research on the codebase using various analysis flags.

This command provides comprehensive analysis capabilities for different aspects of the system.

Given the research request provided as an argument, do this:

1. Run `scripts/deep-research.sh --json "{{args}}"` from repo root and parse JSON for RESEARCH_TYPE, SEARCH_TERM, OUTPUT_FILE, and ANALYSIS_SCOPE. All file paths must be absolute.

2. Based on the research type, execute the appropriate analysis:
   - **-text**: General text search across codebase and documentation
   - **-code**: Code analysis for specific components or functions
   - **-arch**: Architecture analysis for system design and relationships
   - **-perf**: Performance analysis for bottlenecks and optimization
   - **-sec**: Security analysis for vulnerabilities and best practices
   - **-dep**: Dependency analysis for package management and vulnerabilities

3. For each research type, follow the comprehensive analysis protocol:
   - **Initial Scan**: Review documentation, search codebase, map components
   - **External Research**: Search official docs, forums, best practices
   - **Deep Analysis**: Examine implementation details, test coverage, dependencies
   - **Context Building**: Map relationships, document data flow, identify integration points
   - **Quality Assessment**: Review performance, security, error handling, test coverage
   - **Documentation**: Summarize findings, provide recommendations, list resources

4. Generate comprehensive research report:
   - Use `/templates/research-template.md` as the base structure
   - Include overview, technical details, recommendations, and related resources
   - Incorporate external research findings and best practices
   - Document code references, test coverage, and related PRs
   - Provide actionable recommendations and optimization suggestions

5. Save research results to OUTPUT_FILE with proper formatting and structure.

6. Report completion with research type, findings summary, and output file path.

Use absolute paths with the repository root for all file operations to avoid path issues.
"""
