description = "Prepare and execute deployment process. This is the seventh step in the Spec-Driven Development lifecycle."

prompt = """

Prepare and execute deployment process.

This is the seventh step in the Spec-Driven Development lifecycle.

Given the deployment context provided as an argument, do this:

1. Run `scripts/setup-deployment.sh --json` from repo root and parse FEATURE_DIR, DEPLOYMENT_TARGET, and DEPLOYMENT_CONFIG. All paths must be absolute.

2. Load and analyze deployment requirements:
   - Read the feature specification and deployment criteria
   - Review environment configurations
   - Check deployment scripts and configurations
   - Verify production readiness

3. Execute deployment preparation protocol:
   - **Pre-deployment Checks**:
     * Verify all tests pass
     * Check code quality and security
     * Validate configuration settings
     * Review database migrations
   
   - **Build Process**:
     * Compile and build application
     * Run production optimizations
     * Generate deployment artifacts
     * Create deployment packages
   
   - **Environment Setup**:
     * Configure target environment
     * Set up database connections
     * Configure external services
     * Set up monitoring and logging
   
   - **Deployment Execution**:
     * Deploy application components
     * Run database migrations
     * Configure load balancers
     * Set up health checks

4. Generate deployment report:
   - Use `/templates/deployment-template.md` as the base structure
   - Document deployment steps and results
   - Include environment configuration details
   - List deployed components and versions
   - Provide rollback procedures

5. Create deployment artifacts:
   - Generate deployment logs
   - Create environment documentation
   - Set up monitoring dashboards
   - Document operational procedures

6. Save deployment results to DEPLOYMENT_RESULTS_FILE with comprehensive details.

7. Report completion with deployment status, environment details, and access information.

Use absolute paths with the repository root for all file operations to avoid path issues.
"""
