description = "Execute deployment operations and environment management. This command handles deployment operations following the project's deployment guidelines and best practices."

prompt = """

Execute deployment operations and environment management.

This command handles deployment operations following the project's deployment guidelines and best practices.

Given the deployment request provided as an argument, do this:

1. Run `scripts/deployment-guide.sh --json "{{args}}"` from repo root and parse JSON for DEPLOYMENT_TYPE, TARGET_ENV, BUILD_CONFIG, and DEPLOYMENT_STRATEGY. All file paths must be absolute.

2. Based on the deployment type, execute the appropriate deployment operation:
   - **build-application**: Build application for deployment
   - **deploy-staging**: Deploy to staging environment
   - **deploy-production**: Deploy to production environment
   - **rollback-deployment**: Rollback to previous version
   - **health-check**: Verify deployment health
   - **environment-setup**: Set up deployment environment
   - **blue-green-deploy**: Execute blue-green deployment

3. For each deployment, follow the deployment protocol:
   - **Pre-deployment Checks**: Verify build status, run tests, check dependencies
   - **Build Process**: Compile and optimize application
   - **Deployment Execution**: Deploy to target environment
   - **Post-deployment Validation**: Verify deployment success and health
   - **Monitoring Setup**: Configure deployment monitoring

4. Enforce deployment best practices:
   - Use infrastructure as code
   - Implement proper CI/CD pipelines
   - Use containerization
   - Apply security measures
   - Monitor deployment health
   - Plan rollback procedures

5. Generate deployment report:
   - Document deployment steps
   - Report build and deployment status
   - List environment configurations
   - Provide health check results
   - Include monitoring information

6. Report completion with deployment type, success status, and environment details.

Use absolute paths with the repository root for all file operations to avoid path issues.
"""
