description = "Set up and configure development environments. This command handles environment setup operations following the project's environment configuration guidelines and best practices."

prompt = """

Set up and configure development environments.

This command handles environment setup operations following the project's environment configuration guidelines and best practices.

Given the environment request provided as an argument, do this:

1. Run `scripts/environment-setup.sh --json "{{args}}"` from repo root and parse JSON for ENVIRONMENT_TYPE, CONFIG_PROFILE, DEPENDENCIES, and SETUP_MODE. All file paths must be absolute.

2. Based on the environment type, execute the appropriate environment setup:
   - **setup-development**: Set up development environment
   - **setup-staging**: Configure staging environment
   - **setup-production**: Set up production environment
   - **setup-testing**: Configure testing environment
   - **update-environment**: Update existing environment
   - **validate-environment**: Validate environment configuration
   - **clean-environment**: Clean up environment

3. For each environment setup, follow the environment configuration protocol:
   - **Requirements Analysis**: Identify environment requirements
   - **Dependency Installation**: Install required dependencies
   - **Configuration Setup**: Configure environment variables and settings
   - **Service Configuration**: Set up required services
   - **Validation**: Verify environment setup and functionality
   - **Documentation**: Document environment configuration

4. Enforce environment best practices:
   - Use environment-specific configurations
   - Secure sensitive information
   - Use containerization
   - Implement proper networking
   - Monitor environment health
   - Document setup procedures

5. Generate environment report:
   - Document environment configuration
   - List installed dependencies
   - Report service status
   - Provide access information
   - Include troubleshooting guides

6. Report completion with environment type, setup status, and configuration details.

Use absolute paths with the repository root for all file operations to avoid path issues.
"""
