description = "Implement and improve error handling strategies. This command handles error handling operations following the project's error handling guidelines and best practices."

prompt = """

Implement and improve error handling strategies.

This command handles error handling operations following the project's error handling guidelines and best practices.

Given the error handling request provided as an argument, do this:

1. Run `scripts/error-handling.sh --json "{{args}}"` from repo root and parse JSON for ERROR_TYPE, HANDLING_STRATEGY, LOGGING_LEVEL, and RECOVERY_ACTION. All file paths must be absolute.

2. Based on the error handling type, execute the appropriate error handling operation:
   - **analyze-errors**: Analyze existing error patterns
   - **implement-handling**: Implement error handling mechanisms
   - **improve-logging**: Enhance error logging and reporting
   - **setup-monitoring**: Configure error monitoring
   - **create-fallbacks**: Implement fallback mechanisms
   - **test-error-scenarios**: Test error handling scenarios
   - **document-procedures**: Document error handling procedures

3. For each error handling operation, follow the error handling protocol:
   - **Error Analysis**: Identify error patterns and root causes
   - **Strategy Implementation**: Implement appropriate error handling
   - **Logging Enhancement**: Improve error logging and reporting
   - **Monitoring Setup**: Configure error monitoring and alerting
   - **Testing**: Validate error handling effectiveness
   - **Documentation**: Document error handling procedures

4. Enforce error handling best practices:
   - Use appropriate error types
   - Implement graceful degradation
   - Provide meaningful error messages
   - Log errors with context
   - Monitor error rates
   - Plan recovery procedures

5. Generate error handling report:
   - Document error analysis findings
   - List implemented error handling
   - Report error monitoring setup
   - Provide testing results
   - Include troubleshooting guides

6. Report completion with error handling type, implementation status, and monitoring setup.

Use absolute paths with the repository root for all file operations to avoid path issues.
"""
