description = "Execute Git workflow operations and branch management. This command handles Git operations following the project's branching strategy and commit guidelines."

prompt = """

Execute Git workflow operations and branch management.

This command handles Git operations following the project's branching strategy and commit guidelines.

Given the Git operation request provided as an argument, do this:

1. Run `scripts/git-workflow.sh --json "{{args}}"` from repo root and parse JSON for OPERATION_TYPE, BRANCH_NAME, COMMIT_MESSAGE, and TARGET_BRANCH. All file paths must be absolute.

2. Based on the operation type, execute the appropriate Git workflow:
   - **create-feature**: Create new feature branch from develop
   - **create-hotfix**: Create hotfix branch from master
   - **commit-changes**: Stage and commit changes with proper message format
   - **merge-feature**: Merge feature branch to develop
   - **merge-hotfix**: Merge hotfix to master and develop
   - **rebase-branch**: Rebase branch with latest develop
   - **cleanup-branches**: Delete merged branches
   - **resolve-conflicts**: Help resolve merge conflicts

3. For each operation, follow the Git workflow protocol:
   - **Pre-operation Checks**: Verify branch status, check for uncommitted changes
   - **Operation Execution**: Execute the specific Git command with proper parameters
   - **Post-operation Validation**: Verify operation success, check branch status
   - **Cleanup**: Update remote references, clean up temporary files

4. Enforce Git best practices:
   - Use conventional commit message format
   - Follow branch naming conventions
   - Validate commit message structure
   - Check for sensitive information in commits
   - Ensure proper branch protection rules

5. Generate operation report:
   - Document executed commands
   - Report any warnings or errors
   - Provide next steps if needed
   - Update branch status information

6. Report completion with operation type, success status, and any follow-up actions required.

Use absolute paths with the repository root for all file operations to avoid path issues.
"""
