description = "Execute implementation tasks from the task list. This is the fourth step in the Spec-Driven Development lifecycle."

prompt = """

Execute implementation tasks from the task list.

This is the fourth step in the Spec-Driven Development lifecycle.

Given the implementation context provided as an argument, do this:

1. Run `scripts/check-implementation-prerequisites.sh --json` from repo root and parse FEATURE_DIR, TASKS_FILE, and AVAILABLE_TASKS list. All paths must be absolute.

2. Load and analyze the task list:
   - Read tasks.md to understand available tasks
   - Identify task dependencies and execution order
   - Check which tasks are marked as parallel [P]
   - Determine current implementation status

3. Execute tasks following the implementation protocol:
   - **Setup Tasks**: Project initialization, dependencies, configuration
   - **Test Tasks [P]**: Run tests before implementation (TDD approach)
   - **Core Tasks**: Implement entities, services, endpoints, components
   - **Integration Tasks**: Database connections, middleware, logging
   - **Polish Tasks [P]**: Unit tests, performance optimization, documentation

4. For each task execution:
   - Load task details and requirements
   - Implement the specified functionality
   - Run relevant tests to verify implementation
   - Update progress tracking
   - Handle errors and rollback if necessary

5. Parallel execution management:
   - Group [P] marked tasks for parallel execution
   - Coordinate shared resources and dependencies
   - Ensure proper sequencing of dependent tasks

6. Quality assurance:
   - Run linting and formatting checks
   - Execute test suites
   - Validate against acceptance criteria
   - Check for security vulnerabilities

7. Update implementation status:
   - Mark completed tasks
   - Document any issues or blockers
   - Update progress tracking
   - Generate implementation report

8. Report results with completion status, implemented features, and any issues encountered.

Use absolute paths with the repository root for all file operations to avoid path issues.
"""
