description = "Analyze and optimize application performance. This command handles performance analysis and optimization following the project's performance guidelines."

prompt = """

Analyze and optimize application performance.

This command handles performance analysis and optimization following the project's performance guidelines.

Given the performance optimization request provided as an argument, do this:

1. Run `scripts/performance-optimization.sh --json "{{args}}"` from repo root and parse JSON for OPTIMIZATION_TYPE, TARGET_COMPONENT, METRICS_THRESHOLD, and ANALYSIS_SCOPE. All file paths must be absolute.

2. Based on the optimization type, execute the appropriate performance analysis:
   - **analyze-bottlenecks**: Identify performance bottlenecks
   - **optimize-queries**: Optimize database queries
   - **improve-caching**: Enhance caching strategy
   - **optimize-bundle**: Optimize frontend bundle size
   - **memory-analysis**: Analyze memory usage
   - **load-testing**: Perform load testing
   - **monitor-metrics**: Set up performance monitoring

3. For each optimization, follow the performance analysis protocol:
   - **Baseline Measurement**: Establish current performance metrics
   - **Bottleneck Identification**: Find performance issues and bottlenecks
   - **Optimization Implementation**: Apply performance improvements
   - **Validation Testing**: Verify optimization effectiveness
   - **Monitoring Setup**: Configure performance monitoring

4. Enforce performance best practices:
   - Measure before and after optimization
   - Use appropriate profiling tools
   - Implement caching strategies
   - Optimize database queries
   - Minimize bundle sizes
   - Monitor key performance indicators

5. Generate performance report:
   - Document current performance metrics
   - List identified bottlenecks
   - Detail optimization implementations
   - Report performance improvements
   - Provide monitoring recommendations

6. Report completion with optimization type, performance improvements, and monitoring setup status.

Use absolute paths with the repository root for all file operations to avoid path issues.
"""
