description = "Detect and set the active specs workstream context for downstream task commands."

prompt = """

Determine the active spec/workstream and store it for other commands to use by default.

Args (JSON)
------------
{
  "spec_path": "/absolute/path/to/spec/folder",  // optional
  "spec_key": "001-the-calendar-is"               // optional
}

Behavior
--------
1) Resolution order:
   - If spec_path provided, validate it exists and contains task.md.
   - Else if spec_key provided, resolve to /home/spanexx/Desktop/Projects/EventideV1/specs/<spec_key>.
   - Else auto-detect by:
     a) Checking current Git branch for a token matching a subfolder name in /specs.
     b) Scanning open/active files for a path under /specs.
     c) Falling back to the most recently modified /specs/* containing task.md.

2) Persist the resolved context to: .qwen/state/active-spec.json
   {
     "spec_path": "...",
     "task_file": "<spec_path>/task.md",
     "resolved_by": "arg|branch|open_file|mtime"
   }

3) Print the resolved context for visibility.

Conventions
-----------
- Use absolute paths under /home/spanexx/Desktop/Projects/EventideV1 only.
- Do not create a new spec; only detect existing ones.

Examples
--------
// Explicit
{"spec_key":"001-the-calendar-is"}

// Auto-detect
{}

"""


